const initialState = {
  profiles: [
    {id:'TRN-PRO-1001',type:'Sender',name:'Northstar Gig Support',email:'northstar@example.test',phone:'5550101001',status:'Active',created:'01/19/2025',updated:'07/19/2026'},
    {id:'TRN-ACC-001',type:'Driver',name:'Avery Morgan',email:'avery.primary@example.test',phone:'5550101002',status:'Locked',created:'04/12/2025',updated:'07/18/2026',consumer:'Clear',license:'TRN-LIC-001',primary:false,notes:[]},
    {id:'TRN-ACC-002',type:'Driver',name:'Avery Morgan',email:'avery.duplicate@example.test',phone:'5550101002',status:'Active',created:'11/03/2024',updated:'07/18/2026',consumer:'Pending',license:'TRN-LIC-002',primary:false,notes:[]},
    {id:'TRN-ACC-003',type:'Driver',name:'Avery Morgan',email:'avery.old@example.test',phone:'5550101002',status:'Pending',created:'08/22/2023',updated:'06/02/2026',consumer:'Failed',license:'',primary:false,notes:[]}
  ],
  gigs:[{id:'TRN-GIG-169385215',title:'Return to Store',sender:'Northstar Gig Support',state:'Delivered',deadline:'07/21/2026 10:00 AM EDT',offers:4,event:'Delivery Confirmed',support:'TRN-SUP-1N139DFL'}],
  actions:{primary:false,unlocked:false,cleared:false,note:false},hintIndex:0
};
let state = structuredClone(initialState);
const app = document.getElementById('app');
function cloneTemplate(id){return document.getElementById(id).content.cloneNode(true)}
function route(name,id){history.pushState({name,id},'',`#${name}${id?'/'+id:''}`);render(name,id)}
window.addEventListener('popstate',()=>readHash());
function readHash(){const [name='home',id] = location.hash.replace('#','').split('/');render(name||'home',id)}
function bindGlobal(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));const hb=document.getElementById('headerSearchBtn');if(hb)hb.onclick=()=>route('search',document.getElementById('headerSearch').value)}
function render(name,id){app.innerHTML='';if(name==='search')renderSearch(id);else if(name==='profile')renderProfile(id||'TRN-ACC-001');else if(name==='gig')renderGig();else renderHome();bindGlobal()}
function renderHome(){app.appendChild(cloneTemplate('home-template'));document.getElementById('homeSearchBtn').onclick=()=>route('search',document.getElementById('homeSearch').value);document.querySelector('.profile-card').onclick=()=>route('profile','TRN-PRO-1001')}
function renderSearch(query=''){app.appendChild(cloneTemplate('search-template'));const input=document.getElementById('searchInput');input.value=decodeURIComponent(query||'');const draw=()=>{const q=input.value.trim().toLowerCase();const ps=state.profiles.filter(p=>!q||Object.values(p).some(v=>String(v).toLowerCase().includes(q)));document.getElementById('profilesBody').innerHTML=ps.map(p=>`<tr data-id="${p.id}"><td>${p.id}</td><td>${p.type}</td><td>${p.name}</td><td>${p.email}</td><td>${p.phone}</td><td>${p.status}</td><td>${p.created}</td><td>${p.updated}</td></tr>`).join('');document.querySelectorAll('#profilesBody tr').forEach(r=>r.onclick=()=>route('profile',r.dataset.id));const gs=state.gigs.filter(g=>!q||Object.values(g).some(v=>String(v).toLowerCase().includes(q)));document.getElementById('gigsBody').innerHTML=gs.map(g=>`<tr><td>${g.id}</td><td>${g.title}</td><td>${g.sender}</td><td>${g.state}</td><td>${g.deadline}</td><td>${g.offers}</td><td>${g.event}</td><td>${g.support}</td></tr>`).join('');document.querySelectorAll('#gigsBody tr').forEach(r=>r.onclick=()=>route('gig'))};document.getElementById('searchBtn').onclick=draw;draw()}
function renderProfile(id){const p=state.profiles.find(x=>x.id===id)||state.profiles[1];app.appendChild(cloneTemplate('profile-template'));document.getElementById('profileName').textContent=p.name;document.getElementById('profileEmail').textContent=`(${p.email})`;document.getElementById('profileCreated').textContent=`Created ${p.created}`;const pill=document.getElementById('profileStatusPill');pill.textContent=`✓ ${p.status}`;pill.className=`pill ${p.status.toLowerCase()==='locked'?'locked':'active'}`;const rows=[['Account Status',p.status],['Consumer Report Status',p.consumer||'Not applicable'],['Primary Account',p.primary?'Yes':'No'],['Business Name',p.type==='Sender'?'Northstar Support':'Not provided'],['Preferred Name',p.name],['Phone Number',p.phone],['Profile Photo','Unverified'],['Biography','Training-only fictional profile'],['License Information',p.license||'Cleared'],['User ID',p.id],['Created On',p.created],['Updated On',p.updated]];document.getElementById('profileDetails').innerHTML=rows.map(([k,v])=>`<span>${k}</span><strong>${v}</strong>`).join('');document.getElementById('notesList').innerHTML=(p.notes||[]).map(n=>`<li>${n}</li>`).join('')||'<li>No notes yet.</li>';document.getElementById('markPrimaryBtn').onclick=()=>{state.profiles.filter(x=>x.type==='Driver').forEach(x=>x.primary=false);p.primary=true;state.actions.primary=p.id==='TRN-ACC-001';renderProfile(p.id)};document.getElementById('unlockBtn').onclick=()=>{p.status='Active';state.actions.unlocked=p.id==='TRN-ACC-001';renderProfile(p.id)};document.getElementById('clearLicenseBtn').onclick=()=>{p.license='';state.actions.cleared=p.id==='TRN-ACC-002';renderProfile(p.id)};document.getElementById('addNoteBtn').onclick=()=>{const note=prompt('Enter a training note. Include the words “duplicate” and “primary”.','Duplicate account. TRN-ACC-001 retained as primary.');if(note){p.notes=p.notes||[];p.notes.push(note);state.actions.note=p.id==='TRN-ACC-002'&&/duplicate/i.test(note)&&/primary/i.test(note);renderProfile(p.id)}};document.getElementById('resetScenarioBtn').onclick=()=>{state=structuredClone(initialState);route('profile','TRN-ACC-001')};const hints=['Compare consumer-report statuses before choosing the primary account.','The account with the clear consumer report should remain primary.','Clear license information from the duplicate account, then document the primary account ID.'];document.getElementById('hintBtn').onclick=()=>{document.getElementById('hintText').textContent=hints[Math.min(state.hintIndex++,hints.length-1)]};updateProgress()}
function updateProgress(){const items=[['Select TRN-ACC-001 as primary',state.actions.primary],['Unlock TRN-ACC-001',state.actions.unlocked],['Clear license on TRN-ACC-002',state.actions.cleared],['Add duplicate note to TRN-ACC-002',state.actions.note]];document.getElementById('progressList').innerHTML=items.map(([t,d])=>`<li class="${d?'done':''}">${d?'✓':'○'} ${t}</li>`).join('');document.getElementById('completeMessage').hidden=!items.every(x=>x[1])}
function renderGig(){app.appendChild(cloneTemplate('gig-template'));const rows=[['Gig ID','TRN-GIG-169385215'],['Reference ID','TRN-REF-77896544'],['Tracking Number','TRN-TRACK-169385215'],['Sender','Northstar Gig Support'],['Description','Training-only return delivery scenario'],['Gig Size','Medium'],['Offers','4'],['State','Delivered'],['Accepted Driver','avery.driver@example.test'],['Pickup Location','218 Bento Cross Rd, Fiction City, GA 30033'],['Delivery Location','825 Harbor Close, Fiction City, GA 30031'],['Recipient','Jordan Mercado'],['Created On','Jul 19, 2026 9:22 PM EDT'],['Updated On','Jul 19, 2026 10:36 PM EDT']];document.getElementById('gigDetails').innerHTML=rows.map(([k,v])=>`<span>${k}</span><strong>${v}</strong>`).join('')}
readHash();
