const initialProfiles = [
  { id:'TRN-ACC-001', type:'Driver', name:'Avery Morgan', email:'avery.primary@example.test', phone:'5550101002', status:'Locked', created:'Apr 12, 2025', updated:'Jul 20, 2026', consumer:'Clear', license:'TRAINING-LIC-001', primary:false, completedGigs:18, lastGig:'Jul 18, 2026', trustSafety:'No permanent deactivation', notes:[] },
  { id:'TRN-ACC-002', type:'Driver', name:'Avery Morgan', email:'avery.duplicate@example.test', phone:'5550101002', status:'Locked', created:'Jul 18, 2026', updated:'Jul 18, 2026', consumer:'Not started', license:'TRAINING-LIC-002', primary:false, completedGigs:0, lastGig:'None', trustSafety:'No permanent deactivation', notes:[] },
  { id:'TRN-ACC-003', type:'Driver', name:'Avery Morgan', email:'avery.old@example.test', phone:'5550101002', status:'Locked', created:'Jun 19, 2024', updated:'Jan 4, 2025', consumer:'Pending', license:'TRAINING-LIC-003', primary:false, completedGigs:0, lastGig:'None', trustSafety:'No permanent deactivation', notes:[] },
  { id:'TRN-PRO-1001', type:'Sender', name:'Northstar Gig Support', email:'northstar@example.test', phone:'5550101100', status:'Active', created:'Jan 19, 2025', updated:'Jul 19, 2026', consumer:'N/A', license:'N/A', primary:false, completedGigs:'N/A', lastGig:'N/A', trustSafety:'N/A', notes:[] }
];
const gigs=[{id:'TRN-GIG-169385215',title:'Return to Store',sender:'Northstar Gig Support',state:'Delivered',deadline:'Jul 21, 2026 10:00 AM',offers:4,event:'Delivery Confirmed',support:'TRN-SUP-1N139DFL'}];
const hints=[
  'Start with the information the customer provided. What could you use in Global Search?',
  'The customer provided a phone number. Search it and review every related driver profile.',
  'Compare consumer report status, completed Gigs and recent activity before changing any account.',
  'The established profile with the completed consumer report and Gig history should remain the primary account.',
  'Duplicate profiles should remain locked. Clear their license information and document the relationship on every affected profile.'
];
let profiles=[];
let state={route:'landing',activeProfileId:null,query:'',startedAt:null,caseAccepted:false,casePanelOpen:true,caseTab:'reply',messages:[],caseNotes:'',caseFields:{category:'',rootCause:'',gigId:''},hintsUsed:0,reviewedIds:[],actions:[],progress:{},casesCompleted:0,xp:0,readiness:0,streak:0};
const app=document.getElementById('app');
const $=s=>document.querySelector(s);
const clone=v=>JSON.parse(JSON.stringify(v));
function resetCase(){profiles=clone(initialProfiles);Object.assign(state,{activeProfileId:null,query:'',startedAt:Date.now(),caseAccepted:false,casePanelOpen:true,caseTab:'reply',messages:[],caseNotes:'',caseFields:{category:'',rootCause:'',gigId:''},hintsUsed:0,reviewedIds:[],actions:[],progress:{}});}
function template(id){return document.getElementById(id).content.cloneNode(true)}
function go(route,options={}){state.route=route;Object.assign(state,options);render();window.scrollTo({top:0,behavior:'smooth'})}
function bindRoutes(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));}
function record(type,targetId=null){state.actions.push({type,targetId,time:Date.now()});}
function escapeHtml(value){const d=document.createElement('div');d.textContent=value;return d.innerHTML}
function formatPhone(phone){return phone==='5550101002'?'(555) 010-1002':phone}
function updateHeader(){document.getElementById('headerReadiness').textContent=`${state.readiness}%`;document.getElementById('headerXp').textContent=state.xp;document.getElementById('headerStreak').textContent=state.streak;document.getElementById('currentProfileNav').disabled=!state.activeProfileId;}
function render(){app.innerHTML='';if(state.route==='landing')renderLanding();if(state.route==='dashboard')renderDashboard();if(state.route==='search')renderSearch();if(state.route==='profile')renderProfile();if(state.route==='results')renderResults();bindRoutes();updateHeader();bindGlobalControls();}
function bindGlobalControls(){document.querySelector('.brand').onclick=()=>go('landing');document.getElementById('coachToggle').onclick=openCoach;document.querySelectorAll('#openCoachFromNav').forEach(b=>b.onclick=openCoach);document.querySelectorAll('#openCaseFromNav').forEach(b=>{b.onclick=()=>{state.casePanelOpen=true;render();}});}
function renderLanding(){app.append(template('landing-template'));$('#startShiftBtn').onclick=()=>{resetCase();go('dashboard')}}
function renderDashboard(){app.append(template('dashboard-template'));$('#dashboardCases').textContent=`${state.casesCompleted} / 5`;$('#dashboardReadiness').textContent=`${state.readiness}%`;$('#dashboardStreak').textContent=state.streak;$('#dashboardXp').textContent=state.xp;$('#acceptContactBtn').textContent=state.caseAccepted?'Open Active Contact':'Accept Contact';$('#acceptContactBtn').onclick=()=>{state.caseAccepted=true;state.startedAt=state.startedAt||Date.now();record('CONTACT_ACCEPTED');state.casePanelOpen=true;go('search')};mountCasePanel();}
function filteredProfiles(){const q=state.query.trim().toLowerCase();return profiles.filter(p=>!q||[p.id,p.type,p.name,p.email,p.phone,p.status].some(v=>String(v).toLowerCase().includes(q)))}
function filteredGigs(){const q=state.query.trim().toLowerCase();return gigs.filter(g=>!q||Object.values(g).some(v=>String(v).toLowerCase().includes(q)))}
function renderSearch(){app.append(template('search-template'));const input=$('#searchInput');input.value=state.query;const doSearch=()=>{state.query=input.value;if(state.query.replace(/\D/g,'').includes('5550101002')){state.progress.found=true;record('SEARCH_PHONE')}render()};$('#searchBtn').onclick=doSearch;input.onkeydown=e=>{if(e.key==='Enter')doSearch()};const ps=filteredProfiles(),gs=filteredGigs();$('#profileCount').textContent=`${ps.length} result${ps.length===1?'':'s'}`;$('#gigCount').textContent=`${gs.length} result${gs.length===1?'':'s'}`;$('#profilesBody').innerHTML=ps.length?ps.map(p=>`<tr><td><a data-profile="${p.id}">${p.id}</a></td><td>${p.type}</td><td>${p.name}</td><td>${p.email}</td><td>${formatPhone(p.phone)}</td><td><span class="mini-pill ${p.status.toLowerCase()}">${p.status}</span></td><td>${p.completedGigs}</td><td>${p.consumer}</td></tr>`).join(''):'<tr><td colspan="8" class="empty-row">No fictional profiles found.</td></tr>';$('#gigsBody').innerHTML=gs.length?gs.map(g=>`<tr><td>${g.id}</td><td>${g.title}</td><td>${g.sender}</td><td>${g.state}</td><td>${g.deadline}</td><td>${g.offers}</td><td>${g.event}</td><td>${g.support}</td></tr>`).join(''):'<tr><td colspan="8" class="empty-row">No fictional Gigs found.</td></tr>';document.querySelectorAll('[data-profile]').forEach(a=>a.onclick=()=>{state.activeProfileId=a.dataset.profile;if(!state.reviewedIds.includes(a.dataset.profile))state.reviewedIds.push(a.dataset.profile);record('PROFILE_REVIEWED',a.dataset.profile);state.progress.reviewed=state.reviewedIds.filter(id=>id.startsWith('TRN-ACC')).length>=2;go('profile')});mountCasePanel();}
function renderProfile(){const p=profiles.find(x=>x.id===state.activeProfileId)||profiles[0];app.append(template('profile-template'));$('#profileName').textContent=`${p.name} · ${p.id}`;$('#profileEmail').textContent=p.email;$('#profileStatusPill').textContent=p.status;$('#profileStatusPill').className=`pill ${p.status.toLowerCase()}`;$('#profileCreated').textContent=`Created ${p.created}`;$('#profileDetails').innerHTML=detailRows([['Account ID',p.id],['Account status',p.status],['Primary account',p.primary?'Yes':'No'],['Trust & Safety status',p.trustSafety],['Consumer report status',p.consumer],['Completed Gigs',p.completedGigs],['Most recent Gig',p.lastGig],['License information',p.license],['Phone number',formatPhone(p.phone)],['Email',p.email],['Created on',p.created],['Updated on',p.updated]]);$('#notesList').innerHTML=p.notes.length?p.notes.map(n=>`<li>${escapeHtml(n)}</li>`).join(''):'<li>No notes added.</li>';$('#markPrimaryBtn').disabled=p.primary;$('#unlockBtn').disabled=p.status!=='Locked';$('#clearLicenseBtn').disabled=p.license==='None'||p.license==='N/A';$('#markPrimaryBtn').onclick=()=>confirmAction('Mark primary account',`Mark ${p.id} as the primary account?`,()=>actionMarkPrimary(p));$('#unlockBtn').onclick=()=>confirmAction('Unlock account',`Unlock ${p.id}?`,()=>actionUnlock(p));$('#clearLicenseBtn').onclick=()=>confirmAction('Clear license information',`Remove the fictional license information from ${p.id}?`,()=>actionClear(p));$('#addNoteBtn').onclick=()=>openNote(p);$('#addNoteTopBtn').onclick=()=>openNote(p);mountCasePanel();}
function detailRows(rows){return rows.map(([l,v])=>`<span>${l}</span><strong>${v}</strong>`).join('')}
function actionMarkPrimary(p){profiles.forEach(x=>x.primary=x.id===p.id);state.progress.primary=p.id==='TRN-ACC-001';record('MARK_PRIMARY',p.id);renderProfile()}
function actionUnlock(p){p.status='Active';state.progress.unlocked=p.id==='TRN-ACC-001';record('UNLOCK_ACCOUNT',p.id);renderProfile()}
function actionClear(p){p.license='None';record('CLEAR_LICENSE',p.id);const d=profiles.filter(x=>['TRN-ACC-002','TRN-ACC-003'].includes(x.id));state.progress.cleared=d.every(x=>x.license==='None');renderProfile()}
function openNote(p){const d=$('#noteDialog');$('#noteText').value='';d.showModal();$('#saveNoteBtn').onclick=e=>{e.preventDefault();const text=$('#noteText').value.trim();if(!text)return;p.notes.push(text);record('ADD_PROFILE_NOTE',p.id);const primary=profiles.find(x=>x.id==='TRN-ACC-001');const dupNotes=profiles.filter(x=>['TRN-ACC-002','TRN-ACC-003'].includes(x.id)).every(x=>x.notes.some(n=>/duplicate/i.test(n)&&/TRN-ACC-001|primary/i.test(n)));const primaryNote=primary.notes.some(n=>/duplicate/i.test(n)&&/(TRN-ACC-002|TRN-ACC-003)/i.test(n));state.progress.noted=dupNotes&&primaryNote;d.close();renderProfile()}}
function confirmAction(title,text,action){$('#confirmTitle').textContent=title;$('#confirmText').textContent=text;const d=$('#confirmDialog');d.showModal();$('#confirmActionBtn').onclick=e=>{e.preventDefault();d.close();action()}}
function mountCasePanel(){const host=$('#casePanelMount');if(!host)return;if(!state.caseAccepted||!state.casePanelOpen){host.innerHTML=`<div class="case-panel"><div class="case-panel-header"><div><p class="eyebrow">ACTIVE CASE</p><strong>${state.caseAccepted?'SR-102384':'No accepted contact'}</strong></div></div><div class="case-tab-pane"><p class="subtle">${state.caseAccepted?'Open Active Case from the Training navigation.':'Accept the waiting contact from the dashboard to begin.'}</p></div></div>`;return}host.innerHTML='';host.append(template('case-panel-template'));$('#collapseCaseBtn').onclick=()=>{state.casePanelOpen=false;render()};$('#sentMessages').innerHTML=state.messages.map(m=>`<div class="message agent-message"><strong>You</strong><p>${escapeHtml(m.text)}</p></div>`).join('');document.querySelectorAll('[data-case-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.caseTab===state.caseTab);b.onclick=()=>{state.caseTab=b.dataset.caseTab;mountCasePanel()}});renderCaseTab();}
function renderCaseTab(){const mount=$('#caseTabContent');if(state.caseTab==='reply'){mount.innerHTML=`<div class="case-tab-pane"><textarea id="chatReply" rows="4" placeholder="Type your reply to Avery..."></textarea><div class="case-actions"><button class="primary full" id="sendReplyBtn">Send Reply</button></div></div>`;$('#sendReplyBtn').onclick=()=>{const text=$('#chatReply').value.trim();if(!text)return;state.messages.push({text});record('SEND_REPLY');state.progress.responded=/(account|profile|email|locked|unlock|access|sign in|login)/i.test(text);mountCasePanel()}}
if(state.caseTab==='details'){mount.innerHTML=`<div class="case-tab-pane"><div class="field-grid"><div><label>Customer type</label><input value="Driver" disabled></div><div><label>Channel</label><input value="Chat" disabled></div></div><label>Category</label><select id="caseCategory"><option value="">Select category</option><option>Account Management</option><option>Gig Support</option></select><label>Root cause</label><select id="caseRoot"><option value="">Select root cause</option><option>Duplicate Profiles</option><option>Account Lock</option><option>Consumer Report</option></select><label>Gig ID</label><input id="caseGig" placeholder="Not applicable"><button class="secondary full" id="saveCaseDetailsBtn">Save Case Details</button></div>`;$('#caseCategory').value=state.caseFields.category;$('#caseRoot').value=state.caseFields.rootCause;$('#caseGig').value=state.caseFields.gigId;$('#saveCaseDetailsBtn').onclick=()=>{state.caseFields={category:$('#caseCategory').value,rootCause:$('#caseRoot').value,gigId:$('#caseGig').value};state.progress.caseDetails=state.caseFields.category==='Account Management'&&state.caseFields.rootCause==='Duplicate Profiles';record('SAVE_CASE_DETAILS');mountCasePanel()}}
if(state.caseTab==='notes'){mount.innerHTML=`<div class="case-tab-pane"><textarea id="caseNotes" rows="5" placeholder="Document the interaction, investigation and outcome...">${escapeHtml(state.caseNotes)}</textarea><button class="secondary full" id="saveCaseNotesBtn">Save Case Notes</button><button class="primary full" id="closeCaseBtn" style="margin-top:9px">Close Case</button></div>`;$('#saveCaseNotesBtn').onclick=()=>{state.caseNotes=$('#caseNotes').value.trim();state.progress.caseNotes=state.caseNotes.length>=30;record('SAVE_CASE_NOTES');mountCasePanel()};$('#closeCaseBtn').onclick=closeCase}}
function closeCase(){state.caseNotes=$('#caseNotes')?$('#caseNotes').value.trim():state.caseNotes;state.progress.caseNotes=state.caseNotes.length>=30;const required=['found','reviewed','primary','unlocked','cleared','noted','responded','caseDetails','caseNotes'];const complete=required.every(k=>state.progress[k]);if(!complete){alert('The case is not ready to close. Review the customer response, Admin actions, case details and documentation.');return}state.casesCompleted=1;state.xp+=320;state.readiness=Math.min(100,state.readiness+3);state.streak+=1;go('results')}
function openCoach(){const d=$('#coachDialog');$('#coachCases').textContent=`${state.casesCompleted} / 5`;$('#coachHints').textContent=state.hintsUsed;$('#coachStreak').textContent=state.streak;$('#hintText').hidden=true;d.showModal();$('#hintBtn').onclick=()=>{const hint=hints[Math.min(state.hintsUsed,hints.length-1)];state.hintsUsed+=1;$('#coachHints').textContent=state.hintsUsed;$('#hintText').hidden=false;$('#hintText').textContent=hint;record('HINT_USED')};$('#kbaBtn').onclick=()=>{$('#guideDialog').showModal()};$('#resetCaseBtn').onclick=()=>{d.close();resetCase();go('dashboard')}}
function renderResults(){app.append(template('results-template'));const elapsed=Math.max(1,Math.round((Date.now()-state.startedAt)/60000));$('#resultTime').textContent=`${elapsed} min`;const wrongPrimary=state.actions.some(a=>a.type==='MARK_PRIMARY'&&a.targetId!=='TRN-ACC-001');const wrongUnlock=state.actions.some(a=>a.type==='UNLOCK_ACCOUNT'&&a.targetId!=='TRN-ACC-001');$('#processRating').textContent=wrongPrimary||wrongUnlock?'Recovered':'Strong';$('#coachingSummary').textContent=wrongPrimary||wrongUnlock?'You ultimately resolved the case, but made an account change before confirming the correct primary profile. Compare consumer report status and account activity before taking action.':'You compared related profiles, selected the established account, preserved the duplicates, documented the relationship and clearly returned the outcome to the customer.';$('#continueShiftBtn').onclick=()=>go('dashboard');$('#repeatCaseBtn').onclick=()=>{resetCase();go('dashboard')}}
resetCase();state.route='landing';render();
